### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [choikongji/add_nbo#1]
https://github.com/choikongji/add_nbo/commit/f54f4f3fb435a8c88f1402d28c0f565cb239c9fb#r38121735

https://github.com/choikongji/add_nbo/commit/f54f4f3fb435a8c88f1402d28c0f565cb239c9fb#r38121743

**Comment by choikongji** [comment]
done in https://github.com/choikongji/add_nbo/blob/master/main.cpp

**Comment by choikongji** [comment]
done in
https://github.com/choikongji/add_nbo/blob/master/main.cpp

**Comment by snoopspy** [comment]
![image](https://user-images.githubusercontent.com/4080232/78767070-140aed00-79c5-11ea-84df-78244b59be30.png)

댓글이 달리지 않았습니다. issuer가 쓴 comment에 대해 댓글로 어떻게 수정하였는지 commit URL을 달아 주세요. 그래야먄 issuer가 그 URL을 클릭해 보고 확인할 수 있습니다.
